### ISSUE TITLE
check whether directories already exist

### ISSUE THREAD

**Issue by chickymonkeys** [coderigo/stata-git#2]
Hi @coderigo, thank you for your contribution, this package is becoming really useful to me. By the way, I am using your code to install repositories from **gitlab**, and I found out that in each `capture confirm file` command there's a `/nul` missing, in order to recognize the directory as a proper file (e. g. at `line 40` it should be **capture confirm file "\`gitDir'/nul"** instead of just **capture confirm file"\`gitDir'"** in order to get`_rc == 0` if the directory exists). I have tried to change it and it is working.

Moreover, there should be an exception to control for the case in which the repository has not the same name of the program, or there are more .ado files with different names in the repository (I did not find anything of it in the code, but this is just a proposal for an improvement of the program).

Best.

**Comment by coderigo** [comment]
Thanks for the contribution @chickymonkeys. Glad you found this useful. As it happens I've not used Stata for a very long time now and don't have access to a copy anymore. I suspect a lot has changed since I last used it (I wrote this on `v12` and just noticed it's up to `v15`). Your PR looks 👍  though, so I'll go ahead and merge it after bumping the version number.  Thanks again.

As for the repo names not being the same as the program names or multiple `.ado` files: good point. I would make some room to address it but because of the limitations I face. DM me if you are keen to have a go and I can add you as a collaborator to the repo.
